version: "3.7"

services:
  db:
    build:
      context: ./postgres
      dockerfile: db.Dockerfile
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"

  pgadmin:
    container_name: "pgadmin"
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:postgres"

  authorization-server:
    build: ./authorization-server
    container_name: "authorization_server"
    ports:
      - "9091:9091"
    depends_on:
      - db
    links:
      - db

  rental-api:
    build: ./rental-api
    ports:
      - "9090:9090"
    depends_on:
      - db
    links:
      - db

volumes:
#  db-data:
  pgadmin-data:
##  postgres-data:
#  data: {}